In [1]:
import pandas as pd
import glob
import os

In [2]:
# Directory where I-SAFE files are stored
input_dir = "/home/mrc.gm/hsaizonou/an_analysis/prep_isafe_inputs/isafe_results"

In [5]:
ISAFE_THRESHOLD = 0.25

results = []

for file in glob.glob(os.path.join(input_dir, "*.iSAFE.out")):

    fname = os.path.basename(file)
    base = fname.replace(".iSAFE.out", "")

    # Split and remove empty strings to handle double underscores
    parts = [p for p in base.split("_") if p]

    # Extract metadata
    population = parts[0]
    chrom = parts[1]
    start = parts[2]
    end = parts[3]
    region = f"{chrom}:{start}-{end}"

    # Load and clean data
    df = pd.read_csv(file, sep="\t", header=None, comment="#")
    df.columns = ["POS", "iSAFE", "DAF"]

    df = df[df["POS"] != "POS"]

    df["POS"] = df["POS"].astype(int)
    df["iSAFE"] = df["iSAFE"].astype(float)
    df["DAF"] = df["DAF"].astype(float)

    # Filter on iSAFE threshold
    df = df[df["iSAFE"] > ISAFE_THRESHOLD].copy()

    # Add metadata
    df["population"] = population
    df["region"] = region
    df["filename"] = fname

    results.append(df)

# Combine
combined_df = pd.concat(results, ignore_index=True)

# Rank globally
combined_df = combined_df.sort_values("iSAFE", ascending=False).reset_index(drop=True)
combined_df

,POS,iSAFE,DAF,population,region,filename
0,8702553,0.759418,0.931496,Allcountries,2RL:8000000-9852553,Allcountries_2RL_8000000_9852553.iSAFE.out
1,8703059,0.748173,0.905512,Allcountries,2RL:8000000-9852553,Allcountries_2RL_8000000_9852553.iSAFE.out
2,8703055,0.748173,0.905512,Allcountries,2RL:8000000-9852553,Allcountries_2RL_8000000_9852553.iSAFE.out
3,8702578,0.741426,0.868504,Allcountries,2RL:8000000-9852553,Allcountries_2RL_8000000_9852553.iSAFE.out
4,8689600,0.737975,0.796063,Allcountries,2RL:8000000-9852553,Allcountries_2RL_8000000_9852553.iSAFE.out
...,...,...,...,...,...,...
18607,42857226,0.250094,0.500000,Kilifi,2RL:40000000-44000000,Kilifi_2RL_40000000_44000000.iSAFE.out
18608,8597493,0.250080,0.314173,Allcountries,2RL:8000000-9852553,Allcountries_2RL_8000000_9852553.iSAFE.out
18609,8850497,0.250072,0.648305,Ogun,2RL:8000000-9852553,Ogun_2RL_8000000_9852553.iSAFE.out
18610,8941516,0.250062,0.557377,Nzerekore,2RL:8000000-9852553,Nzerekore_2RL_8000000_9852553.iSAFE.out
18611,8924996,0.250009,0.538265,Guinea,2RL:8000000-9852553,Guinea_2RL_8000000_9852553.iSAFE.out

In [6]:
combined_df.to_csv("combined_isafe_results_af1_new_threshold_0.25.csv")

In [2]:
combined_df = pd.read_csv("combined_isafe_results_af1_new_threshold_0.25.csv")

In [3]:
set(combined_df['region'].to_list())

{'2RL:40000000-44000000',
 '2RL:57629228-58000000',
 '2RL:8000000-9852553',
 '2RL:80479740-80828789',
 '3RL:12761557-14664404',
 'X:14432245-15024921'}

adding the region lacking

In [6]:
# Directory where I-SAFE files are stored
input_dir = "/home/mrc.gm/hsaizonou/an_analysis/prep_isafe_inputs_one_region/isafe_results_one_region"

In [7]:
ISAFE_THRESHOLD = 0.25

results = []

for file in glob.glob(os.path.join(input_dir, "*.iSAFE.out")):

    fname = os.path.basename(file)
    base = fname.replace(".iSAFE.out", "")

    # Split and remove empty strings to handle double underscores
    parts = [p for p in base.split("_") if p]

    # Extract metadata
    population = parts[0]
    chrom = parts[1]
    start = parts[2]
    end = parts[3]
    region = f"{chrom}:{start}-{end}"

    # Load and clean data
    df = pd.read_csv(file, sep="\t", header=None, comment="#")
    df.columns = ["POS", "iSAFE", "DAF"]

    df = df[df["POS"] != "POS"]

    df["POS"] = df["POS"].astype(int)
    df["iSAFE"] = df["iSAFE"].astype(float)
    df["DAF"] = df["DAF"].astype(float)

    # Filter on iSAFE threshold
    df = df[df["iSAFE"] > ISAFE_THRESHOLD].copy()

    # Add metadata
    df["population"] = population
    df["region"] = region
    df["filename"] = fname

    results.append(df)
    
# Combine
combined_df = pd.concat(results, ignore_index=True)

# Rank globally
combined_df = combined_df.sort_values("iSAFE", ascending=False).reset_index(drop=True)
combined_df

,POS,iSAFE,DAF,population,region,filename
0,76617450,0.569336,0.537037,Oyo,2RL:76000000-76838987,Oyo__2RL_76000000_76838987.iSAFE.out
1,76617474,0.569336,0.537037,Oyo,2RL:76000000-76838987,Oyo__2RL_76000000_76838987.iSAFE.out
2,76612099,0.562672,0.500000,Oyo,2RL:76000000-76838987,Oyo__2RL_76000000_76838987.iSAFE.out
3,76609844,0.562672,0.500000,Oyo,2RL:76000000-76838987,Oyo__2RL_76000000_76838987.iSAFE.out
4,76609127,0.562672,0.500000,Oyo,2RL:76000000-76838987,Oyo__2RL_76000000_76838987.iSAFE.out
...,...,...,...,...,...,...
3824,76630270,0.250315,0.237245,Guinea,2RL:76000000-76838987,Guinea__2RL_76000000_76838987.iSAFE.out
3825,76630164,0.250315,0.237245,Guinea,2RL:76000000-76838987,Guinea__2RL_76000000_76838987.iSAFE.out
3826,76478989,0.250293,0.337008,Allcountries,2RL:76000000-76838987,Allcountries__2RL_76000000_76838987.iSAFE.out
3827,76688576,0.250265,0.673729,Ogun,2RL:76000000-76838987,Ogun__2RL_76000000_76838987.iSAFE.out
3828,76481647,0.250137,0.259563,Nzerekore,2RL:76000000-76838987,Nzerekore__2RL_76000000_76838987.iSAFE.out

In [8]:
set(combined_df['region'].to_list())

{'2RL:76000000-76838987'}

In [9]:
combined_df.to_csv("/home/mrc.gm/hsaizonou/an_analysis/for_one_region_combined_isafe_results_af1_new_threshold_0.25.csv")

In [10]:
first_combined = pd.read_csv("combined_isafe_results_af1_new_threshold_0.25.csv")

In [11]:
all_combined  = pd.concat([first_combined, combined_df], ignore_index=True)

In [12]:
all_combined.to_csv("/home/mrc.gm/hsaizonou/an_analysis/all_combined_region_isafe_results_af1_new_threshold_0.25.csv")